-- ============================================
-- 国际结算模块 - 数据库初始化脚本
-- ============================================
USE forex_settlement;

DROP TABLE IF EXISTS t_letter_of_credit;
CREATE TABLE t_letter_of_credit (
    id BIGINT NOT NULL COMMENT '主键ID',
    lc_no VARCHAR(64) NOT NULL COMMENT '信用证编号',
    customer_id BIGINT NOT NULL COMMENT '客户ID',
    lc_type VARCHAR(30) NOT NULL COMMENT '类型: IMPORT=进口信用证 EXPORT=出口信用证 STANDBY=备用信用证 DOMESTIC=国内信用证',
    lc_direction VARCHAR(20) NOT NULL COMMENT '方向: ISSUE=开立 ADVISE=通知 BANK_ISSUE=银行开立',
    lc_amount DECIMAL(22,6) NOT NULL COMMENT '信用证金额',
    lc_currency VARCHAR(10) NOT NULL COMMENT '信用证币种',
    tolerance_pct DECIMAL(5,2) DEFAULT 0 COMMENT '金额浮动比例%',
    applicant_info JSON NOT NULL COMMENT '申请人信息',
    beneficiary_info JSON NOT NULL COMMENT '受益人信息',
    issuing_bank_info JSON DEFAULT NULL COMMENT '开证行信息',
    advising_bank_info JSON DEFAULT NULL COMMENT '通知行信息',
    confirming_bank_info JSON DEFAULT NULL COMMENT '保兑行信息',
    issue_date DATE NOT NULL COMMENT '开证日期',
    expiry_date DATE NOT NULL COMMENT '有效期',
    expiry_place VARCHAR(50) DEFAULT NULL COMMENT '到期地点',
    latest_ship_date DATE DEFAULT NULL COMMENT '最迟装运日',
    presentation_period INT DEFAULT 21 COMMENT '交单期(天)',
    available_with VARCHAR(50) DEFAULT 'ANY_BANK' COMMENT '兑用银行',
    available_by VARCHAR(30) NOT NULL DEFAULT 'SIGHT' COMMENT '兑用方式: SIGHT=即期 ACCEPTANCE=承兑 NEGOTIATION=议付 DEFERRED=延期',
    draft_tenor VARCHAR(50) DEFAULT NULL COMMENT '汇票期限',
    partial_shipment VARCHAR(10) DEFAULT 'ALLOWED' COMMENT '分批装运: ALLOWED/NOT_ALLOWED',
    transshipment VARCHAR(10) DEFAULT 'ALLOWED' COMMENT '转运: ALLOWED/NOT_ALLOWED',
    port_of_loading VARCHAR(100) DEFAULT NULL COMMENT '装运港',
    port_of_discharge VARCHAR(100) DEFAULT NULL COMMENT '卸货港',
    goods_description TEXT COMMENT '货物描述',
    documents_required TEXT COMMENT '单据要求',
    additional_conditions TEXT COMMENT '附加条款',
    confirmation_instruction VARCHAR(20) DEFAULT 'WITHOUT' COMMENT '保兑指示: WITH/WITHOUT',
    charge_bearer VARCHAR(30) DEFAULT 'APPLICANT' COMMENT '费用承担: APPLICANT/BENEFICIARY',
    lc_status VARCHAR(30) NOT NULL DEFAULT 'DRAFT' COMMENT '状态: DRAFT=草稿 SUBMITTED=已提交 ISSUED=已开立 ADVISED=已通知 AMENDED=已修改 DOCS_PRESENTED=已交单 DOCS_CHECKED=已审单 DISCREPANCY=不符点 ACCEPTED=已承兑 PAID=已付款 DISCHARGED=已销记 CANCELLED=已取消',
    swift_ref VARCHAR(64) DEFAULT NULL COMMENT 'SWIFT报文参考号',
    margin_pct DECIMAL(5,2) DEFAULT 0 COMMENT '保证金比例%',
    margin_amount DECIMAL(22,6) DEFAULT 0 COMMENT '保证金金额',
    fee_amount DECIMAL(22,6) DEFAULT 0 COMMENT '手续费',
    operator_id BIGINT DEFAULT NULL COMMENT '操作员ID',
    remark VARCHAR(1000) DEFAULT NULL COMMENT '备注',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    version INT NOT NULL DEFAULT 0,
    deleted TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_lc_no (lc_no),
    KEY idx_customer_id (customer_id),
    KEY idx_lc_status (lc_status),
    KEY idx_issue_date (issue_date),
    KEY idx_expiry_date (expiry_date),
    KEY idx_swift_ref (swift_ref)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='信用证表';

DROP TABLE IF EXISTS t_documentary_collection;
CREATE TABLE t_documentary_collection (
    id BIGINT NOT NULL COMMENT '主键ID',
    collection_no VARCHAR(64) NOT NULL COMMENT '托收编号',
    customer_id BIGINT NOT NULL COMMENT '客户ID',
    collection_type VARCHAR(30) NOT NULL COMMENT '类型: IMPORT=进口代收 EXPORT=出口托收',
    collection_form VARCHAR(30) NOT NULL COMMENT '方式: DP=付款交单 DA=承兑交单',
    collection_amount DECIMAL(22,6) NOT NULL COMMENT '托收金额',
    collection_currency VARCHAR(10) NOT NULL COMMENT '币种',
    drawer_info JSON DEFAULT NULL COMMENT '出票人信息',
    drawee_info JSON NOT NULL COMMENT '付款人信息',
    remitting_bank VARCHAR(200) DEFAULT NULL COMMENT '委托行',
    collecting_bank VARCHAR(200) DEFAULT NULL COMMENT '代收行',
    documents_list TEXT COMMENT '单据清单',
    collection_status VARCHAR(30) NOT NULL DEFAULT 'DRAFT' COMMENT '状态: DRAFT=草稿 SUBMITTED=已提交 DOCS_RECEIVED=已收单 PRESENTED=已提示 ACCEPTED=已承兑 PAID=已付款 DISHONORED=拒绝付款 CANCELLED=已取消',
    swift_ref VARCHAR(64) DEFAULT NULL,
    operator_id BIGINT DEFAULT NULL,
    remark VARCHAR(1000) DEFAULT NULL,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    version INT NOT NULL DEFAULT 0,
    deleted TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_collection_no (collection_no),
    KEY idx_customer_id (customer_id),
    KEY idx_collection_status (collection_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='跟单托收表';

DROP TABLE IF EXISTS t_bank_guarantee;
CREATE TABLE t_bank_guarantee (
    id BIGINT NOT NULL COMMENT '主键ID',
    guarantee_no VARCHAR(64) NOT NULL COMMENT '保函编号',
    customer_id BIGINT NOT NULL COMMENT '客户ID(申请人)',
    guarantee_type VARCHAR(30) NOT NULL COMMENT '类型: BID_BOND=投标保函 PERFORMANCE_BOND=履约保函 ADVANCE_PAYMENT=预付款保函 PAYMENT_GUARANTEE=付款保函 WARRANTY=质量保函 OTHER=其他',
    guarantee_amount DECIMAL(22,6) NOT NULL COMMENT '保函金额',
    guarantee_currency VARCHAR(10) NOT NULL COMMENT '币种',
    beneficiary_info JSON NOT NULL COMMENT '受益人信息',
    issue_date DATE NOT NULL COMMENT '开立日期',
    effective_date DATE NOT NULL COMMENT '生效日期',
    expiry_date DATE NOT NULL COMMENT '到期日期',
    claim_expiry_date DATE DEFAULT NULL COMMENT '索赔到期日',
    counter_guarantee_no VARCHAR(64) DEFAULT NULL COMMENT '反担保编号',
    guarantee_format VARCHAR(30) DEFAULT 'DIRECT' COMMENT '格式: DIRECT=直开 INDIRECT=转开',
    guarantee_status VARCHAR(30) NOT NULL DEFAULT 'DRAFT' COMMENT '状态: DRAFT=草稿 SUBMITTED=已提交 ISSUED=已开立 CLAIMED=已索赔 EXPIRED=已到期 CANCELLED=已取消 DISCHARGED=已销记',
    fee_amount DECIMAL(22,6) DEFAULT 0 COMMENT '手续费',
    commission_rate DECIMAL(8,6) DEFAULT NULL COMMENT '费率',
    operator_id BIGINT DEFAULT NULL,
    swift_ref VARCHAR(64) DEFAULT NULL,
    remark VARCHAR(1000) DEFAULT NULL,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    version INT NOT NULL DEFAULT 0,
    deleted TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_guarantee_no (guarantee_no),
    KEY idx_customer_id (customer_id),
    KEY idx_guarantee_status (guarantee_status),
    KEY idx_expiry_date (expiry_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='银行保函表';
