-- Journal entry table. 会计分录表.
CREATE TABLE IF NOT EXISTS `t_journal_entry` (
    `id`                  BIGINT        NOT NULL AUTO_INCREMENT COMMENT '主键 ID',
    `voucher_no`          VARCHAR(32)   NOT NULL COMMENT '凭证号',
    `voucher_date`        DATE          NOT NULL COMMENT '凭证日期',
    `fiscal_period`       VARCHAR(16)   NOT NULL COMMENT '会计期间 yyyyMM',
    `biz_type`            VARCHAR(32)   NOT NULL COMMENT '业务类型',
    `biz_no`              VARCHAR(64)   COMMENT '业务编号',
    `currency`            VARCHAR(8)    NOT NULL COMMENT '币种',
    `amount`              DECIMAL(20,2) NOT NULL COMMENT '金额',
    `entry_direction`     VARCHAR(8)    NOT NULL COMMENT '方向: DEBIT/CREDIT',
    `account_code`        VARCHAR(32)   NOT NULL COMMENT '科目代码',
    `account_name`        VARCHAR(128)  COMMENT '科目名称',
    `opposite_account_code` VARCHAR(32) COMMENT '对方科目代码',
    `summary`             VARCHAR(512)  COMMENT '摘要',
    `entry_status`        VARCHAR(20)   NOT NULL DEFAULT 'DRAFT' COMMENT '状态: DRAFT/POSTED/REVERSED',
    `reversed_voucher_no` VARCHAR(32)   COMMENT '冲正凭证号',
    `posted_time`         DATETIME      COMMENT '过账时间',
    `operator_id`         BIGINT        COMMENT '操作员 ID',
    `version`             INT           NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    `deleted`             TINYINT       NOT NULL DEFAULT 0 COMMENT '逻辑删除 0-未删除 1-已删除',
    `create_time`         DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time`         DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_voucher_no` (`voucher_no`),
    KEY `idx_voucher_date` (`voucher_date`),
    KEY `idx_fiscal_period` (`fiscal_period`),
    KEY `idx_biz_no` (`biz_no`),
    KEY `idx_entry_status` (`entry_status`),
    KEY `idx_account_code` (`account_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='会计分录表';
